# Generated by Django 5.2.6 on 2025-09-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_siero', models.DecimalField(decimal_places=2, help_text='Volume di siero in litri', max_digits=10)),
                ('costo_impianto', models.DecimalField(decimal_places=2, help_text="Costo dell'impianto in euro", max_digits=12)),
                ('costi_operativi_annui', models.DecimalField(decimal_places=2, help_text='Costi operativi annui in euro', max_digits=12)),
                ('prezzo_vendita_proteine', models.DecimalField(decimal_places=2, help_text='Prezzo di vendita proteine in €/kg', max_digits=8)),
                ('resa_proteine', models.DecimalField(decimal_places=4, help_text='Resa in kg di proteine per litro di siero', max_digits=6)),
                ('prezzo_vendita_siero', models.DecimalField(decimal_places=2, default=0.5, help_text='Prezzo di vendita del siero in €/litro', max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Input Simulazione',
                'verbose_name_plural': 'Input Simulazioni',
            },
        ),
    ]
