# Generated by Django 5.2.6 on 2025-09-25 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20250925_1123'),
    ]

    operations = [
    ]
