# Generated by Django 5.2.6 on 2025-09-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20250925_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationinput',
            name='campo_select',
            field=models.CharField(blank=True, choices=[('', "Seleziona un'opzione"), ('opzione1', 'Opzione Uno'), ('opzione2', 'Opzione Due'), ('opzione3', 'Opzione Tre')], help_text='Campo di selezione personalizzabile', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='simulationinput',
            name='capacita_investimento',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Capacità di investimento in euro (opzionale)', max_digits=12),
        ),
    ]
