# Generated by Django 4.2.24 on 2025-09-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_simulationinput_campo_select_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationinput',
            name='costo_distribuzione',
            field=models.DecimalField(decimal_places=2, default=10000, help_text='Costo di distribuzione in euro', max_digits=10),
        ),
        migrations.AddField(
            model_name='simulationinput',
            name='personale_disponibile',
            field=models.CharField(blank=True, choices=[('', 'Seleziona disponibilità personale'), ('Si', 'Sì'), ('No', 'No')], help_text="Personale disponibile per gestire l'impianto", max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='simulationinput',
            name='spazio_disponibile',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Spazio disponibile in metri quadri', max_digits=8),
        ),
        migrations.AddField(
            model_name='simulationinput',
            name='tempistiche',
            field=models.CharField(blank=True, choices=[('', 'Seleziona tempistiche'), ('breve', 'Breve (< 6 mesi)'), ('media', 'Media (6-12 mesi)'), ('lunga', 'Lunga (> 12 mesi)')], help_text='Tempistiche di implementazione', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='simulationinput',
            name='campo_select',
            field=models.CharField(blank=True, choices=[('', "Seleziona un'opzione"), ('Si', 'Si'), ('No', 'No')], help_text='Campo di selezione personalizzabile', max_length=20, null=True),
        ),
    ]
